import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@component/styles/Home.module.css";
import { BrowserCodeReader, BrowserQRCodeReader } from "@zxing/browser";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [cam,setCam] = useState("")
  const codeReader = new BrowserQRCodeReader();
  useEffect(() => {
    const detectInputDevices = async () => {
      const videoInputDevices = await BrowserCodeReader.listVideoInputDevices();
      console.log(videoInputDevices)
      const selectedDevice  = videoInputDevices[0].deviceId
      setCam(selectedDevice)
    };
    detectInputDevices();
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <video id={cam}></video>
      </main>
    </>
  );
}
